<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIeaDtOg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIeaDtOg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIeaDtOg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIeaDtOg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIeaDtOg\App_KernelDevDebugContainer([
    'container.build_hash' => 'IeaDtOg',
    'container.build_id' => '7221076b',
    'container.build_time' => 1641656973,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIeaDtOg');
